#web容器配置
server:
  context-path: /
  port: 80
#定义环境引用的配置文件
spring:
  application:
    name: super-boot-sleuth-center
    index: ${random.int}
  sleuth:
    enabled: false
  datasource:
    schema[0]: classpath:/zipkin.sql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/super_boot_sleuth?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: superboot
    password: 123456
    initialize: true
    continue-on-error: true
  #热加载配置
  devtools:
    remote:
      secret: thisismysecret
  cloud:
    #启用消息追踪
    bus:
      trace:
        enabled: true
  #配置消息总线
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
#关闭安全认证
management:
  security:
    enabled: false
zipkin:
  storage:
    type: mysql
#启用调试模式
debug: true
#日志配置
logging:
  config: classpath:log4j2-prod.xml
eureka:
  instance:
    #心跳时间间隔
    lease-renewal-interval-in-seconds: 10
    #无心跳多久后,该服务失效
    lease-expiration-duration-in-seconds: 30
    appname: 链路中心
#Twitter_Snowflake 序列号生成器配置
Snowflake:
  #工作中心ID 0-31
  workerId: 0
  #数据中心ID(0~31)
  datacenterId: 0