#web容器配置
server:
  context-path: /
  port: 9081
#启用调试模式
#debug: true
#日志配置
logging:
  config: classpath:log4j2-dev.xml
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
       defaultZone: http://ywgit:YWGit0755@localhost:1111/eureka/
spring:
  #配置消息中心
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  redis:
#    cluster:
#      nodes: 127.0.0.1:7000, 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005
#      pool:
#        max-active: 10
#        max-wait: 10000
#        max-idle: 20
#        min-idle: 5
#      cache-expire: 1800
#      timeout: 10000
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/jpatest
#    username: root
#    password: 123456
#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true
#  jackson:
#    serialization:
#      indent_output: true
#关闭安全认证
management:
  security:
    enabled: false