spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: NON_NULL
    redis:
        database: 1
        host: 127.0.0.1
        pool:
            max-active: 20
    datasource:
      name: test
      url: jdbc:mysql://localhost:3306/invengo_auth?useUnicode=true&characterEncoding=UTF8
      username: root
      password: 123456
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
    zipkin:
        enabled: true
    sleuth:
        sampler:
            percentage: 1
    cloud: 
      bus: 
        trace: 
          enabled: true

mybatis:
    basepackage: org.jtech.auth.mapper
    xmlLocation: classpath:mapper/**/*.xml
    mapper-locations: "classpath*:mapper/*.xml"



ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

server:
  port: 9777

management:
  security:
    enabled: false



eureka:
  instance:
    hostname: localhost
    health-check-url-path: /health
    status-page-url-path: /info
  client:
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
    #zhongye_611@163.com:zy1985611@
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:8761/eureka/

jwt:
  token-header: Authorization
  expire: 3600
  rsa-secret: xx1WET12^%3^(WE45

client:
  id: jtech-auth
  secret: 123456
  token-header: client-token
  expire: 7200
  rsa-secret: x2318^^(*WRYQWR(QW&T
  
security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:123456}